# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 'Build'

on:
  push:
    branches: '**'

  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
